
export const GET_ALL_DOGS = 'GET_ALL_DOGS';
export const GET_DOG_DETAIL = 'GET_DOG_DETAIL';
export const ORDER = 'ORDER';
export const ORDER_BY_WEIGHT = 'ORDER_BY_WEIGHT';
export const FILTER_BY_TEMPERAMENTS = 'FILTER_BY_TEMPERAMENTS';
export const FILTER_FROM_DOGS = 'FILTER_FROM_DOGS';
export const ADD_DOG = 'ADD_DOG';
export const GET_DOGS_NAME = 'GET_DOGS_NAME';
export const GET_ALL_TEMPERAMENTS = 'GET_ALL_TEMPERAMENTS';
export const CLEAN_DETAIL = 'CLEAN_DETAIL';
export const GET_DOGS_BREED = 'GET_DOGS_BREED';
export const CLEAN_FILTER = 'CLEAN_FILTER';